[package]
name = "psyche-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
hf-hub = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }