default:
    just --list

# Build & test & check format - what runs in CI
check: build-all-flake-outputs
    # run checks
    nix flake check |& nom

# Build all flake outputs in one command (no checks)
build-all-flake-outputs:
    nix flake show --json | jq -r '\
    	(.packages."x86_64-linux" | keys[] | ".#" + .),\
    	(.devShells."x86_64-linux" | keys[] | ".#devShells.\"x86_64-linux\"." + .),\
    	(.nixosConfigurations | keys[] | ".#nixosConfigurations." + . + ".config.system.build.toplevel")\
    ' | xargs nom build --impure

# Build the centralized client Docker image
build-docker-centralized-client:
    nom build .#docker-psyche-centralized-client --out-link nix-results/docker-psyche-centralized-client
    docker load < nix-results/docker-psyche-centralized-client

# Build the solana client Docker image
build-docker-solana-client:
    ../scripts/coordinator-address-check.sh
    nom build .#docker-psyche-solana-client --out-link nix-results/docker-psyche-solana-client
    docker load < nix-results/docker-psyche-solana-client

# Build the image for the solana client used for testing
build-docker-test-client:
    nix build .#docker-psyche-solana-test-client --out-link nix-results/docker-psyche-solana-test-client
    docker load < nix-results/docker-psyche-solana-test-client

# Build the image for the solana vaidator used for testing
build-docker-solana-test-vaidator:
    PSYCHE_HOME=$(realpath ..) nix build .#docker-psyche-solana-test-validator --out-link nix-results/docker-psyche-solana-test-validator --impure
    docker load < nix-results/docker-psyche-solana-test-validator
