[package]
name = "psyche-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = {workspace = true}
psyche-core = {path = "../core"}
psyche-coordinator = {path = "../coordinator"}
psyche-tui = {path = "../tui"}