[workspace]
members = ["architectures/*/*", "shared/*"]
resolver = "2"

[workspace.dependencies]

psyche-coordinator = { path = "./shared/coordinator" }
psyche-core = { path = "./shared/core" }
psyche-data-provider = { path = "./shared/data-provider" }
psyche-network = { path = "./shared/network" }
psyche-serde = { path = "./shared/serde" }
psyche-modeling = { path = "./shared/modeling" }
psyche-tui = { path = "./shared/tui" }
psyche-watcher = { path = "./shared/watcher" }

tokio = { version = "1", features = [
    "io-util",
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "time",
] }
tokio-stream = "0.1"
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.28"
tracing = "0.1.40"
bytes = "1.7.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
postcard = { version = "1.0.10", features = ["use-std"] }
sha2 = "0.10.8"
futures-util = "0.3.30"
chrono = "0.4.38"
anchor-lang = "0.29.0"
fast-math = "0.1"
async-trait = "0.1.82"
iroh = "0.24.0"
memmap2 = { version = "0.9.3", features = ["stable_deref_trait"] }
indicatif = "0.17.5"
tokenizers = { version = "0.20.0", default-features = false, features = ["onig"] }
tch = { git = "https://github.com/LaurentMazare/tch-rs.git", rev = "9c498e6dcb83cebaf450fb4bfe0f265d660041b3" }
torch-sys = { git = "https://github.com/LaurentMazare/tch-rs.git", rev = "9c498e6dcb83cebaf450fb4bfe0f265d660041b3" }


# solana-program uses curve25519-dalek v3.2.1, which pins zeroize <1.4 for MSRV cares.
# we don't care about that MSRV guarantee, so we override zeroize dep to be simply "=1"
[patch.crates-io]
curve25519-dalek = { git = "https://github.com/NousResearch/curve25519-dalek.git", rev = "20f6f1540c8ce7fcd54c33470e06032946b2a143" }
