services:
  psyche-run-owner:
    image: psyche-client
    build:
      context: .
      target: test
    depends_on:
      psyche-solana-test-validator:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - "config/client/.env"
    entrypoint: ["/bin/sh", "-c", "sleep 10 && ./usr/local/run-owner-entrypoint.sh"]
    networks:
      - psyche-test-network

  psyche-test-client:
    image: psyche-client
    build:
      context: .
      target: test
    depends_on:
      psyche-run-owner:
        condition: service_completed_successfully
    deploy:
      replicas: ${NUM_REPLICAS:-1}
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ID=${ID:-""}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "~/.config/solana/id.json:/usr/local/id.json"
    env_file:
      - "config/client/.env"
    networks:
      - psyche-test-network

  psyche-solana-test-validator:
    image: psyche_solana
    container_name: psyche-solana-test-validator
    build:
      context: .
      dockerfile: psyche_solana.Dockerfile
    ports:
      - "8899:8899"
      - "8900:8900"
    networks:
      - psyche-test-network

networks:
  psyche-test-network:
    driver: bridge
