services:
  psyche-client:
    image: psyche-client
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "~/.config/solana/id.json:/usr/local/id.json"
    env_file:
      - "config/client/client.env"
