version: "3"

tasks:
  # General check for mindless complete verification
  check:
    cmds:
      - task fmt
      - task lint
      - task test

  # Formatting
  fmt:
    cmds:
      - cargo +nightly fmt

  # Linting
  lint:
    cmds:
      - cargo +nightly clippy --all-targets -- --deny=warnings --allow=unexpected-cfgs

  # Testing
  test:
    cmds:
      - cargo +nightly test
