version: "3"

tasks:
  # General check for mindless complete verification
  check:
    cmds:
      - task fmt
      - task test
      - task lint

  # Testing
  test:
    cmds:
      - cargo +nightly test

  # Linting
  lint:
    cmds:
      - cargo +nightly clippy --all-targets

  # Formatting
  fmt:
    cmds:
      - cargo +nightly fmt
