name: "Maximize build space"
description: "Remove unnecessary files and clean up space on runner"
runs:
  using: "composite"
  steps:
    - name: Maximize build space
      shell: bash
      run: |
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
        df -h
