[package]
name = "psyche-core"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_os = "solana"))'.dependencies]
sha2 = "0.10.6"

[target.'cfg(target_os = "solana")'.dependencies]
solana-program = "1.18"
