receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 10s
    send_batch_size: 512

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Useful for debugging to see logs in the collector's stdout
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug] # Send to both Loki and debug output

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] # Send traces to Jaeger and debug output
