[package]
name = "expand-distro"
version = "0.1.0"
edition = "2021"

[dependencies]
psyche-client.workspace = true
psyche-modeling.workspace = true
anyhow.workspace = true
postcard.workspace = true
tch.workspace = true

toml = "0.8.19"
