version: "3"

tasks:
  # General check for mindless complete verification
  check:
    cmds:
      - task fmt
      - task lint
      - task test

  # Formating everything
  fmt:
    cmds:
      - task authorizer_fmt
      - task coordinator_fmt
      - task treasurer_fmt
      - task tooling_fmt
      - task mining_pool_fmt

  # Linting everything
  lint:
    cmds:
      - task authorizer_lint
      - task coordinator_lint
      - task treasurer_lint
      - task tooling_lint
      - task mining_pool_lint

  # Testing everything
  test:
    cmds:
      - task tooling_test
      - task mining_pool_test

  # Authorizer
  authorizer_fmt:
    dir: "{{ .TASKFILE_DIR }}/solana-authorizer"
    cmds:
      - task fmt
  authorizer_lint:
    dir: "{{ .TASKFILE_DIR }}/solana-authorizer"
    cmds:
      - task lint

  # Coordinator
  coordinator_fmt:
    dir: "{{ .TASKFILE_DIR }}/solana-coordinator"
    cmds:
      - task fmt
  coordinator_lint:
    dir: "{{ .TASKFILE_DIR }}/solana-coordinator"
    cmds:
      - task lint

  # Treasurer
  treasurer_fmt:
    dir: "{{ .TASKFILE_DIR }}/solana-treasurer"
    cmds:
      - task fmt
  treasurer_lint:
    dir: "{{ .TASKFILE_DIR }}/solana-treasurer"
    cmds:
      - task lint

  # Tooling
  tooling_fmt:
    dir: "{{ .TASKFILE_DIR }}/solana-tooling"
    cmds:
      - task fmt
  tooling_lint:
    dir: "{{ .TASKFILE_DIR }}/solana-tooling"
    cmds:
      - task lint
  tooling_test:
    dir: "{{ .TASKFILE_DIR }}/solana-tooling"
    cmds:
      - task test

  # Mining-Pool
  mining_pool_fmt:
    dir: "{{ .TASKFILE_DIR }}/solana-mining-pool"
    cmds:
      - task fmt
  mining_pool_lint:
    dir: "{{ .TASKFILE_DIR }}/solana-mining-pool"
    cmds:
      - task lint
  mining_pool_test:
    dir: "{{ .TASKFILE_DIR }}/solana-mining-pool"
    cmds:
      - task test
