{
 "title": "Clients",
 "time": { "from": "2025-07-22T20:20:50.068Z", "to": "2025-07-22T20:21:32.925Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "clients",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Round step",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "psyche_round_step{exported_instance=\"$clients\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gossip neighbors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "psyche_gossip_neighbors{exported_instance=\"$clients\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Training completed in step",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{instance=\"$clients\"} |= `Got training output, DisTrO results generated`"
      }
     ]
    }
   ]
  },
  {
   "title": "P2P model sharing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "P2P downloaded parameters (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "psyche_p2p_model_params_downloaded{exported_instance=\"$clients\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "P2P failed downloads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "psyche_p2p_params_download_failed_counter_total{exported_instance=\"$clients\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 123 },
     "repeat": "clients",
     "targets": [
      {
       "direction": "backward",
       "expr": "{instance=\"$clients\"}"
      }
     ]
    }
   ]
  }
 ]
}