[package]
name = "psyche-modeling"
version = "0.1.0"
edition = "2021"

[dependencies]
psyche-core = { path = "../core" }
psyche-data-provider = { path = "../data-provider" }
hf-hub = { git = "https://github.com/huggingface/hf-hub.git", rev = "a66bdcf2f2664a55ab3a1415184c7aebd8ac4ed5" }
tch = { git = "https://github.com/jquesnelle/tch-rs.git", rev = "4803ea0ba6288a7723941f9394fa46b684cf9977" }
torch-sys = { git = "https://github.com/jquesnelle/tch-rs.git", rev = "4803ea0ba6288a7723941f9394fa46b684cf9977" }
rand.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
memmap2.workspace = true
byteorder = "1.4.3"
safetensors = "0.3.0"
tokenizers = { version = "0.20.0", default-features = false, features = ["onig"] }


# for examples
[dev-dependencies]
clap = { workspace = true }
