{
 "title": "Clients",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "clients",
    "query": {
     "query": "label_values(psyche_gossip_neighbors,service_instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "psyche_participating_in_round{service_instance_id=\"$clients\"}",
     "legendFormat": "{{service_instance_id}}"
    }
   ]
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Round step",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "psyche_round_step{service_instance_id=\"$clients\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip neighbors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "psyche_gossip_neighbors{service_instance_id=\"$clients\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training completed in step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_instance_id=\"$clients\"}"
    }
   ]
  },
  {
   "title": "Training round duration",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "psyche_last_train_time_seconds{service_instance_id=\"$clients\"}",
     "legendFormat": "time"
    }
   ]
  },
  { "title": "P2P model sharing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "P2P downloaded parameters (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "psyche_p2p_model_params_downloaded{service_instance_id=\"$clients\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "P2P failed downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "psyche_p2p_params_download_failed_counter_total{service_instance_id=\"$clients\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "repeat": "clients",
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"$clients\"}"
    }
   ]
  }
 ]
}