{
 "title": "Runs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": {
     "query": "label_values(psyche_gossip_neighbors,run_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Round step",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(psyche_round_step{run_id=\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip neighbors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "psyche_gossip_neighbors{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training completed in step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{run_id=\"$run_id\"}"
    }
   ]
  },
  {
   "title": "Training round duration",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "psyche_last_train_time_seconds{run_id=\"$run_id\"}",
     "legendFormat": "time"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "psyche_cpu_usage_percent{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "psyche_memory_usage_bytes{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "psyche_gpu_usage_percent{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "psyche_gpu_memory{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "psyche_gpu_temp{run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "repeat": "clients",
   "targets": [
    {
     "direction": "backward",
     "expr": "{level=~\".+\"} |= `` | json | resources_run_id=\"$run_id\""
    }
   ]
  }
 ]
}