[package]
name = "psyche-coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
psyche-core.workspace = true
async-trait.workspace = true
anchor-lang.workspace = true
bytemuck.workspace = true
serde_with.workspace = true
serde.workspace = true
cfg_eval = "0.1.2"
ts-rs.workspace = true
