name: 'Wait for Garnix CI'
description: 'Wait for Garnix CI checks to complete'
inputs:
  timeout-minutes:
    description: 'Maximum time to wait in minutes'
    required: false
    default: '50'
  package:
    description: 'Name of the package to wait for'
    required: false
    default: 'docker-psyche-solana-test-client-no-python [x86_64-linux]'
runs:
  using: 'composite'
  steps:
    - name: Wait for All Garnix checks
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        SHA="${{ github.event.pull_request.head.sha || github.sha }}"
        echo "Waiting for 'All Garnix checks' on commit $SHA"
        TOTAL_ATTEMPTS=$(( ${{ inputs.timeout-minutes }} * 2 ))

        GARNIX_SUITE_ID=""

        for i in $(seq 1 $TOTAL_ATTEMPTS); do
          if [ -z "$GARNIX_SUITE_ID" ]; then
            GARNIX_SUITE_ID=$(gh api repos/${{ github.repository }}/commits/$SHA/check-suites --jq '.check_suites[] | select(.app.name == "Garnix CI") | .id')
            
            if [ -z "$GARNIX_SUITE_ID" ]; then
              echo "No Garnix CI check suite found yet, waiting... (attempt $i/$TOTAL_ATTEMPTS)"
              sleep 10
              continue
            fi
            
            echo "Found Garnix CI check suite: $GARNIX_SUITE_ID"
          fi
          
          CHECK=$(gh api repos/${{ github.repository }}/check-suites/$GARNIX_SUITE_ID/check-runs --jq '.check_runs[] | select(.name == "package ${{ inputs.package }}") | {name: .name, status: .status, conclusion: .conclusion}')
          
          if [ -z "$CHECK" ]; then
            echo "No 'package ${{ inputs.package }}' found yet, waiting..."
            sleep 10
            continue
          fi

          STATUS=$(echo "$CHECK" | jq -r '.status')
          CONCLUSION=$(echo "$CHECK" | jq -r '.conclusion')

          if [ "$CONCLUSION" = "null" ]; then
            echo "Garnix check for image generation: $STATUS (conclusion: pending)"
          fi

          if [ "$STATUS" = "completed" ]; then
            if [ "$CONCLUSION" = "success" ]; then
              echo "Image generation job in Garnix passed!"
              exit 0
            else
              echo "Image generation job in Garnix failed with conclusion: $CONCLUSION"
              exit 1
            fi
          fi

          echo "Waiting for 'package ${{ inputs.package }}' to complete... (attempt $i/$TOTAL_ATTEMPTS)"
          sleep 10

        done
        echo "Timeout waiting for 'All Garnix checks'"
        exit 1
