[package]
name = "psyche-data-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
hf-hub = { git = "https://github.com/huggingface/hf-hub.git", rev = "a66bdcf2f2664a55ab3a1415184c7aebd8ac4ed5" }
tokio.workspace = true
psyche-coordinator = { path = "../coordinator" }
psyche-core = { path = "../core" }
psyche-watcher = { path = "../watcher" }
async-trait.workspace = true
tracing.workspace = true
anyhow.workspace = true
memmap2.workspace = true
rand_chacha = "0.3.1"
rand.workspace = true
tokio-util = { version = "0.7.12", features = ["codec"] }
futures = "0.3.30"
serde.workspace = true

[dev-dependencies]
psyche-tui = { path = "../tui" }
