#!/usr/bin/env bash
# Run the Docker-based model sharing test.
#
# Generates a docker-compose file with individual sharer services so each
# can have a unique ID and optional bandwidth throttling.
#
# Usage:
#   ./run.sh                                        # 1 sharer, 5 downloaders
#   ./run.sh --sharers 3 --slow-sharers 1           # 3 sharers, last 1 throttled
#   ./run.sh --sharers 2 --slow-sharers 1 --slow-rate 50
#   ./run.sh --direct                               # single shared network (no relay)
#   ./run.sh --params 20 --size 100 --downloaders 3

set -euo pipefail
cd "$(dirname "$0")"

NUM_PARAMS=10
PARAM_SIZE_MB=200
NUM_SHARERS=1
NUM_DOWNLOADERS=5
MAX_CONCURRENT=4
DISCOVERY_MODE=n0
RELAY_KIND=psyche
SLOW_SHARERS=0
SLOW_RATE_KB=100
DIRECT=false
RELAY_ONLY=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --params) NUM_PARAMS="$2"; shift 2 ;;
        --size) PARAM_SIZE_MB="$2"; shift 2 ;;
        --sharers) NUM_SHARERS="$2"; shift 2 ;;
        --downloaders) NUM_DOWNLOADERS="$2"; shift 2 ;;
        --max-concurrent) MAX_CONCURRENT="$2"; shift 2 ;;
        --discovery) DISCOVERY_MODE="$2"; shift 2 ;;
        --relay) RELAY_KIND="$2"; shift 2 ;;
        --slow-sharers) SLOW_SHARERS="$2"; shift 2 ;;
        --slow-rate) SLOW_RATE_KB="$2"; shift 2 ;;
        --direct) DIRECT=true; shift ;;
        --relay-only) RELAY_ONLY=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ "$SLOW_SHARERS" -gt "$NUM_SHARERS" ]; then
    echo "Error: --slow-sharers ($SLOW_SHARERS) cannot exceed --sharers ($NUM_SHARERS)"
    exit 1
fi

LOG="/tmp/model_sharing_test_$(date +%s).log"
COMPOSE_FILE="/tmp/model_sharing_compose_$$.yml"

if [ "$DIRECT" = true ]; then
    NET_MODE="direct (single shared network)"
else
    NET_MODE="isolated (separate networks, relay-only)"
fi

echo "=== Model Sharing Test ==="
echo "  Network:        $NET_MODE"
echo "  Sharers:        $NUM_SHARERS (${SLOW_SHARERS} slow at ${SLOW_RATE_KB} KB/s)"
echo "  Parameters:     $NUM_PARAMS x ${PARAM_SIZE_MB}MB"
echo "  Downloaders:    $NUM_DOWNLOADERS"
echo "  Max concurrent: $MAX_CONCURRENT"
echo "  Discovery:      $DISCOVERY_MODE"
echo "  Relay:          $RELAY_KIND"
echo "  Relay-only:     $RELAY_ONLY"
echo "  Log file:       $LOG"
echo ""

# ---------------------------------------------------------------------------
# Generate docker-compose YAML with individual sharer services
# ---------------------------------------------------------------------------
generate_compose() {
    local slow_start=$((NUM_SHARERS - SLOW_SHARERS))

    cat <<'HEADER'
# Auto-generated by run.sh — do not edit manually.
services:
HEADER

    # --- Sharer services ---
    for i in $(seq 0 $((NUM_SHARERS - 1))); do
        local slow_flags=""
        if [ "$i" -ge "$slow_start" ] && [ "$SLOW_SHARERS" -gt 0 ]; then
            slow_flags="--slow --slow-rate-kb=${SLOW_RATE_KB}"
        fi

        local relay_only_flag=""
        if [ "$RELAY_ONLY" = true ]; then
            relay_only_flag="--relay-only"
        fi

        local network="sharer-net"
        if [ "$DIRECT" = true ]; then
            network="shared-net"
        fi

        cat <<EOF
  sharer-${i}:
    build:
      context: ../../../..
      dockerfile: shared/network/examples/docker-isolated-test/Dockerfile
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        model_sharing_test --mode=sharer \\
          --sharer-id=${i} \\
          --num-parameters=${NUM_PARAMS} \\
          --parameter-size-mb=${PARAM_SIZE_MB} \\
          --discovery-mode=${DISCOVERY_MODE} \\
          --relay-kind=${RELAY_KIND} \\
          ${slow_flags} ${relay_only_flag} &
        PID=\$\$!
        while [ ! -f /tmp/sharer_addr_${i}.json ]; do sleep 0.5; done
        cp /tmp/sharer_addr_${i}.json /shared/sharer_addr_${i}.json
        wait \$\$PID
    volumes:
      - sharer-addr:/shared
    environment:
      - RUST_LOG=\${RUST_LOG:-info}
    networks:
      - ${network}
    healthcheck:
      test: ["CMD-SHELL", "test -f /shared/sharer_addr_${i}.json"]
      interval: 2s
      timeout: 2s
      retries: 60
      start_period: 5s

EOF
    done

    # --- Downloader service ---
    local dl_network="downloader-net"
    if [ "$DIRECT" = true ]; then
        dl_network="shared-net"
    fi

    local relay_only_flag=""
    if [ "$RELAY_ONLY" = true ]; then
        relay_only_flag='      - "--relay-only"'
    fi

    cat <<EOF
  downloader:
    build:
      context: ../../../..
      dockerfile: shared/network/examples/docker-isolated-test/Dockerfile
    command:
      - "--mode=downloader"
      - "--num-downloaders=1"
      - "--num-parameters=${NUM_PARAMS}"
      - "--parameter-size-mb=${PARAM_SIZE_MB}"
      - "--max-concurrent-downloads=${MAX_CONCURRENT}"
      - "--discovery-mode=${DISCOVERY_MODE}"
      - "--relay-kind=${RELAY_KIND}"
      - "--sharer-addr=/shared"
EOF

    if [ -n "$relay_only_flag" ]; then
        echo "$relay_only_flag"
    fi

    cat <<EOF
    volumes:
      - sharer-addr:/shared:ro
    environment:
      - RUST_LOG=\${RUST_LOG:-info}
    networks:
      - ${dl_network}
    depends_on:
EOF

    for i in $(seq 0 $((NUM_SHARERS - 1))); do
        cat <<EOF
      sharer-${i}:
        condition: service_healthy
EOF
    done

    cat <<EOF
    deploy:
      replicas: ${NUM_DOWNLOADERS}

volumes:
  sharer-addr:

networks:
EOF

    if [ "$DIRECT" = true ]; then
        cat <<'EOF'
  shared-net:
    driver: bridge
EOF
    else
        cat <<'EOF'
  sharer-net:
    driver: bridge
  downloader-net:
    driver: bridge
EOF
    fi
}

generate_compose > "$COMPOSE_FILE"

# Project directory so relative paths (build context) resolve correctly
PROJ_DIR="$(pwd)"
DC="docker compose -f $COMPOSE_FILE --project-directory $PROJ_DIR"

cleanup() {
    echo ""
    echo "Cleaning up..."
    $DC down -v 2>/dev/null || true
    rm -f "$COMPOSE_FILE"
}
trap cleanup EXIT

echo "Building Docker image (first run will compile from source)..."
$DC build 2>&1 | tee -a "$LOG"

echo ""
echo "Starting test..."
$DC up --abort-on-container-exit 2>&1 | tee -a "$LOG"

echo ""
echo "Done. Full log at: $LOG"
