[config]
warmup_time = 30
cooldown_time = 30
rounds_per_epoch = 8
max_round_train_time = 30
round_witness_time = 3
min_clients = 3
init_min_clients = 3
verification_percent = 0
witness_nodes = 3
global_batch_size_start = 10
global_batch_size_end = 10
global_batch_size_warmup_tokens = 0
total_steps = 25000

[model.LLM]
architecture = "HfLlama"
data_type = "Pretraining"
max_seq_len = 2048
cold_start_warmup_steps = 0
data_location = "Dummy"

[model.LLM.checkpoint.Dummy]
repo_id = ""

[model.LLM.lr_schedule.Cosine]
base_lr = 4.0e-4
warmup_steps = 250
warmup_init_lr = 0.0
total_steps = 25000
final_lr = 4.0e-5
[model.LLM.optimizer.Distro]
clip_grad_norm = 1.0
compression_decay = 0.999
compression_chunk = 64
compression_topk = 8
quantize_1bit = true
