[package]
name = "psyche-centralized-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
serde.workspace = true
psyche-coordinator.workspace = true
psyche-network.workspace = true
psyche-core.workspace = true
