{
 "title": "Psyche",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "psyche_memory_usage_bytes{deployment_environment_name=\"production\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "title": "Current Step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "psyche_round_step{deployment_environment_name=\"production\"} != 0",
     "legendFormat": "{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Completed Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "psyche_downloads_finished_total{deployment_environment_name=\"production\"}",
     "legendFormat": "{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Gossip Neighbors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "psyche_gossip_neighbors{deployment_environment_name=\"production\"}",
     "legendFormat": "{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Psyche CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "psyche_cpu_usage_percent{deployment_environment_name=\"production\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}