{
 "title": "Runs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": {
     "query": "label_values(target_info,run_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Round step",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(psyche_round_step * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip neighbors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "psyche_gossip_neighbors * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training completed in step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "psyche_total_tokens * on(instance) group_left(run_id) target_info {run_id = \"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Training round duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "psyche_last_train_time_seconds * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(target_info{run_id=\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Psyche", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Apply Message Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(psyche_apply_message_success_total[$__rate_interval]) * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apply Message Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(psyche_apply_message_failure_total[$__rate_interval]) * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apply Message Ignored Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(psyche_apply_message_ignored_total[$__rate_interval]) * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broadcasts Seen Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(psyche_broadcasts_seen_total[$__rate_interval]) * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downloads Completed Rate",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(psyche_downloads_finished_total[$__rate_interval]) * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "time"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "psyche_cpu_usage_percent * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "psyche_memory_usage_bytes * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "psyche_gpu_usage_percent * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "psyche_gpu_memory * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "psyche_gpu_temp * on(instance) group_left(run_id) target_info {run_id=\"$run_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "repeat": "clients",
   "targets": [
    {
     "direction": "backward",
     "expr": "{level=~\".+\"} |= `` | json | resources_run_id=\"$run_id\""
    }
   ]
  }
 ]
}