version: "3"

tasks:
  # General check for mindless complete verification
  check:
    cmds:
      - task fmt
      - task lint
      - task test

  # Formatting
  fmt:
    cmds:
      - cargo +nightly fmt

  # Linting
  lint:
    cmds:
      - cargo clippy --all-targets --
        --deny=warnings
        --allow=unexpected-cfgs
        --allow=clippy::bool_assert_comparison

  # Testing
  test:
    cmds:
      - cargo test
