version: "3"

tasks:
  check:
    cmds:
      - task fmt
      - task test
      - task lint

  fmt:
    cmds:
      - cargo +nightly fmt

  test:
    cmds:
      - cargo test

  lint:
    cmds:
      - cargo +nightly clippy --all-targets
