name: Build Solana Test Validator Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-validator-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            download-buffer-size = 524288000
            accept-flake-config = true
            substituters = https://cache.nixos.org/ https://cache.garnix.io/ https://nix-community.cachix.org
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
          sudo chmod +x /usr/local/bin/just

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Solana Test Validator Image
        run: |
          # Show available space
          df -h

          # Build the image
          just nix build_docker_solana_test_validator

          # Tag and push the image
          docker tag psyche-solana-test-validator:latest ghcr.io/${{ github.repository_owner }}/psyche-solana-test-validator:${{ github.sha }}
          docker tag psyche-solana-test-validator:latest ghcr.io/${{ github.repository_owner }}/psyche-solana-test-validator:latest

          docker push ghcr.io/${{ github.repository_owner }}/psyche-solana-test-validator:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/psyche-solana-test-validator:latest

          echo "Image pushed: ghcr.io/${{ github.repository_owner }}/psyche-solana-test-validator:${{ github.sha }}"
