name: Decentralized Integration Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-two-clients-three-epochs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Replace your disk cleanup with Nothing but Nix
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave' # ~115GB, removes large packages but preserves core functionality
          nix-permission-edict: true # Make /nix writable by user
          witness-carnage: true # Optional: see what's being removed
          root-safe-haven: '2048' # Keep 2GB safe on root
          mnt-safe-haven: '1024' # Keep 1GB safe on mnt

      # Install Nix AFTER Nothing but Nix
      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            download-buffer-size = 524288000
            accept-flake-config = true
            substituters = https://cache.nixos.org/ https://cache.garnix.io/ https://nix-community.cachix.org
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      # Check if Docker survived and reinstall if needed
      - name: Setup Docker
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker was removed, reinstalling..."
            # Remove conflicting packages first
            sudo apt-get remove -y containerd containerd.io runc || true
            sudo apt-get autoremove -y || true

            # Clean install using official Docker method
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc

            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

            sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi
          docker --version

          # Install docker-compose if not present
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          docker-compose --version

          # Final cleanup
          docker system prune -af

          # Show available space
          df -h

      - name: Run decentralized integration test
        run: |
          nix develop .#psyche-cpu --command just decentralized-integration-test-cpu test_two_clients_three_epochs_run
