name: Decentralized Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-two-clients-three-epochs:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Additional disk cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af
          df -h

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            download-buffer-size = 524288000
            accept-flake-config = true
            substituters = https://cache.nixos.org/ https://cache.garnix.io/ https://nix-community.cachix.org
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Setup Docker
        run: |
          # Docker is already available in GitHub Actions
          docker --version
          # Install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          docker system prune -af

      - name: Install Solana and Anchor
        run: |
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env

          # Install Solana CLI
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.18/install)"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

          # Install Anchor CLI
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --force

      - name: Build Anchor programs
        run: |
          source ~/.cargo/env
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          cd architectures/decentralized/solana-coordinator && anchor build
          cd architectures/decentralized/solana-authorizer && anchor build

      - name: Build Docker images and run test
        run: |
          nix build .#docker-psyche-solana-test-client --out-link nix-results/docker-psyche-solana-test-client
          nix-results/docker-psyche-solana-test-client | docker load
          PSYCHE_HOME=$(realpath .) nix build .#docker-psyche-solana-test-validator --out-link nix-results/docker-psyche-solana-test-validator --impure
          nix-results/docker-psyche-solana-test-validator | docker load
          source ~/.cargo/env
          cargo test --release -p psyche-decentralized-testing --test integration_tests -- --nocapture "test_two_clients_three_epochs_run"
