name: Download Images and Test

on:
  workflow_run:
    workflows:
      ['Build Solana Test Client Image', 'Build Solana Test Validator Image']
    types:
      - completed
    branches: [main]

env:
  DISABLE_FLASH_ATTN: 1

jobs:
  download-images:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download client image artifact
        uses: actions/download-artifact@v4
        with:
          name: solana-test-client-${{ github.event.workflow_run.head_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Download validator image artifact
        uses: actions/download-artifact@v4
        with:
          name: solana-test-validator-${{ github.event.workflow_run.head_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Load Docker images
        run: |
          # Load client image
          echo "Loading client image..."
          docker load < client-image.tar

          # Load validator image
          echo "Loading validator image..."
          gunzip -c validator-image.tar.gz | docker load

          # Verify images loaded
          docker images
