name: Solana integration test one clients three epochs run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-one-clients-three-epochs-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Check initial disk space
        run: |
          echo "=== Initial disk usage ==="
          df -h
          echo "=== Docker info ==="
          docker info | grep -i "docker root dir" || true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: |
            download-buffer-size = 524288000
            accept-flake-config = true
            substituters = https://cache.nixos.org/ https://cache.garnix.io/ https://nix-community.cachix.org
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
          sudo chmod +x /usr/local/bin/just

      # Step 1: Build Anchor Programs
      - name: Build Anchor Programs
        run: |
          echo "Building Solana Coordinator"
          nix develop --command bash -c "cd architectures/decentralized/solana-coordinator && anchor build"

          echo "Building Solana Authorizer"
          nix develop --command bash -c "cd architectures/decentralized/solana-authorizer && anchor build"

          echo "=== Built Coordinator artifacts ==="
          ls -la architectures/decentralized/solana-coordinator/target/deploy/

          echo "=== Built Authorizer artifacts ==="
          ls -la architectures/decentralized/solana-authorizer/target/deploy/

      # Memory cleanup after Anchor build
      - name: Clean Anchor build
        run: |
          # Keep only the deploy artifacts we need, remove intermediate build files
          echo "=== Cleaning Anchor build artifacts (keeping deploy and idl folders) ==="

          # For coordinator - keep entire deploy folder but remove intermediate builds
          find architectures/decentralized/solana-coordinator/target -mindepth 1 -maxdepth 1 ! -name 'deploy' ! -name 'idl' -exec rm -rf {} + 2>/dev/null || true

          # For authorizer - keep entire deploy folder but remove intermediate builds
          find architectures/decentralized/solana-authorizer/target -mindepth 1 -maxdepth 1 ! -name 'deploy' ! -name 'idl' -exec rm -rf {} + 2>/dev/null || true

          # Clean nix store garbage aggressively
          nix-collect-garbage -d
          nix store optimise

          echo "=== Disk usage after Anchor cleanup ==="
          df -h

      # Step 2: Build Solana Test Validator Image
      - name: Build Solana Test Validator Image
        run: |
          export PSYCHE_HOME=$(pwd)

          echo "=== Disk space before validator build ==="
          df -h

          # Build and load in one command
          nix build .#docker-psyche-solana-test-validator --impure --out-link result && ./result | docker load

          echo "=== Disk space after validator build ==="
          df -h

      # Memory cleanup after validator build
      - name: Clean validator build artifacts
        run: |
          # Remove nix build result
          rm -f result

          # Clean nix store garbage
          nix-collect-garbage -d
          nix store optimise

          # Remove temp files
          sudo rm -rf /tmp/* 2>/dev/null || true

          echo "=== Docker images after validator build ==="
          docker images

          echo "=== Disk usage after validator cleanup ==="
          df -h

      # Step 3: Build Solana Test Client Image
      - name: Build Solana Test Client Image
        run: |
          echo "=== Disk space before client build ==="
          df -h

          nix build .#docker-psyche-solana-test-client-no-python --out-link nix-results/docker-psyche-solana-test-client-no-python
          nix-results/docker-psyche-solana-test-client-no-python | docker load
          rm -rf nix-results/docker-psyche-solana-test-client-no-python

          echo "=== Disk space after client build ==="
          df -h

      # Clean Nix store after client build
      - name: Clean after client build
        run: |
          # Clean nix store garbage
          nix-collect-garbage -d
          nix store optimise

          # Remove temp files
          sudo rm -rf /tmp/* 2>/dev/null || true

          echo "=== Disk space after cleanup ==="
          df -h

      - name: Verify Docker images exist
        run: |
          echo "=== Checking for required Docker images ==="
          docker images
          docker images | grep psyche-solana-test-validator || (echo "ERROR: psyche-solana-test-validator image not found" && exit 1)
          docker images | grep psyche-solana-test-client-no-python || (echo "ERROR: psyche-solana-test-client-no-python image not found" && exit 1)
          echo "All required images are present"

          echo "=== Final disk usage before tests ==="
          df -h

      # Step 4: Run Integration Tests
      - name: Run integration test
        run: |
          nix develop --command cargo test --release -p psyche-decentralized-testing --test integration_tests -- --nocapture "test_one_clients_three_epochs_run"
